/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                color1: {
                    DEFAULT: "hsl(var(--color-1))",
                    foreground: "hsl(var(--color-1-foreground))",
                },
                color2: {
                    DEFAULT: "hsl(var(--color-2))",
                    foreground: "hsl(var(--color-2-foreground))",
                },
                color3: {
                    DEFAULT: "hsl(var(--color-3))",
                    foreground: "hsl(var(--color-3-foreground))",
                },
                color4: {
                    DEFAULT: "hsl(var(--color-4))",
                    foreground: "hsl(var(--color-4-foreground))",
                },
                color5: {
                    DEFAULT: "hsl(var(--color-5))",
                    foreground: "hsl(var(--color-5-foreground))",
                },
                color6: {
                    DEFAULT: "hsl(var(--color-6))",
                    foreground: "hsl(var(--color-6-foreground))",
                },
                color7: {
                    DEFAULT: "hsl(var(--color-7))",
                    foreground: "hsl(var(--color-7-foreground))",
                },
                color8: {
                    DEFAULT: "hsl(var(--color-8))",
                    foreground: "hsl(var(--color-8-foreground))",
                },
                color9: {
                    DEFAULT: "hsl(var(--color-9))",
                    foreground: "hsl(var(--color-9-foreground))",
                },
                color10: {
                    DEFAULT: "hsl(var(--color-10))",
                    foreground: "hsl(var(--color-10-foreground))",
                },
                border: "hsl(var(--border))",
                red: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                rose: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                pink: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                fuchsia: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                purple: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                violet: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                indigo: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                blue: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                sky: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                cyan: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                teal: {
                    DEFAULT: "hsl(var(--color-4))",
                    50: "hsl(var(--color-4) / 0.1)",
                    100: "hsl(var(--color-4) / 0.15)",
                    200: "hsl(var(--color-4) / 0.25)",
                    300: "hsl(var(--color-4) / 0.4)",
                    400: "hsl(var(--color-4) / 0.6)",
                    500: "hsl(var(--color-4) / 0.8)",
                    600: "hsl(var(--color-4))",
                    700: "hsl(var(--color-4))",
                    800: "hsl(var(--color-4))",
                    900: "hsl(var(--color-4))",
                    950: "hsl(var(--color-4))",
                },

                emerald: {
                    DEFAULT: "hsl(var(--color-3))",
                    50: "hsl(var(--color-3) / 0.1)",
                    100: "hsl(var(--color-3) / 0.15)",
                    200: "hsl(var(--color-3) / 0.25)",
                    300: "hsl(var(--color-3) / 0.4)",
                    400: "hsl(var(--color-3) / 0.6)",
                    500: "hsl(var(--color-3) / 0.8)",
                    600: "hsl(var(--color-3))",
                    700: "hsl(var(--color-3))",
                    800: "hsl(var(--color-3))",
                    900: "hsl(var(--color-3))",
                    950: "hsl(var(--color-3))",
                },

                green: {
                    DEFAULT: "hsl(var(--color-3))",
                    50: "hsl(var(--color-3) / 0.1)",
                    100: "hsl(var(--color-3) / 0.15)",
                    200: "hsl(var(--color-3) / 0.25)",
                    300: "hsl(var(--color-3) / 0.4)",
                    400: "hsl(var(--color-3) / 0.6)",
                    500: "hsl(var(--color-3) / 0.8)",
                    600: "hsl(var(--color-3))",
                    700: "hsl(var(--color-3))",
                    800: "hsl(var(--color-3))",
                    900: "hsl(var(--color-3))",
                    950: "hsl(var(--color-3))",
                },

                lime: {
                    DEFAULT: "hsl(var(--color-3))",
                    50: "hsl(var(--color-3) / 0.1)",
                    100: "hsl(var(--color-3) / 0.15)",
                    200: "hsl(var(--color-3) / 0.25)",
                    300: "hsl(var(--color-3) / 0.4)",
                    400: "hsl(var(--color-3) / 0.6)",
                    500: "hsl(var(--color-3) / 0.8)",
                    600: "hsl(var(--color-3))",
                    700: "hsl(var(--color-3))",
                    800: "hsl(var(--color-3))",
                    900: "hsl(var(--color-3))",
                    950: "hsl(var(--color-3))",
                },

                yellow: {
                    DEFAULT: "hsl(var(--color-3))",
                    50: "hsl(var(--color-3) / 0.1)",
                    100: "hsl(var(--color-3) / 0.15)",
                    200: "hsl(var(--color-3) / 0.25)",
                    300: "hsl(var(--color-3) / 0.4)",
                    400: "hsl(var(--color-3) / 0.6)",
                    500: "hsl(var(--color-3) / 0.8)",
                    600: "hsl(var(--color-3))",
                    700: "hsl(var(--color-3))",
                    800: "hsl(var(--color-3))",
                    900: "hsl(var(--color-3))",
                    950: "hsl(var(--color-3))",
                },

                amber: {
                    DEFAULT: "hsl(var(--color-3))",
                    50: "hsl(var(--color-3) / 0.1)",
                    100: "hsl(var(--color-3) / 0.15)",
                    200: "hsl(var(--color-3) / 0.25)",
                    300: "hsl(var(--color-3) / 0.4)",
                    400: "hsl(var(--color-3) / 0.6)",
                    500: "hsl(var(--color-3) / 0.8)",
                    600: "hsl(var(--color-3))",
                    700: "hsl(var(--color-3))",
                    800: "hsl(var(--color-3))",
                    900: "hsl(var(--color-3))",
                    950: "hsl(var(--color-3))",
                },

                orange: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                slate: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                gray: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                zinc: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                neutral: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },

                stone: {
                    DEFAULT: "hsl(var(--color-5))",
                    50: "hsl(var(--color-5) / 0.1)",
                    100: "hsl(var(--color-5) / 0.15)",
                    200: "hsl(var(--color-5) / 0.25)",
                    300: "hsl(var(--color-5) / 0.4)",
                    400: "hsl(var(--color-5) / 0.6)",
                    500: "hsl(var(--color-5) / 0.8)",
                    600: "hsl(var(--color-5))",
                    700: "hsl(var(--color-5))",
                    800: "hsl(var(--color-5))",
                    900: "hsl(var(--color-5))",
                    950: "hsl(var(--color-5))",
                },
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
            },
        },
    },
    plugins: [],
}
